//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.yrtech.bentley.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketActionAfter7
    {
        public int MarketActionId { get; set; }
        public string HightLights { get; set; }
        public string ImproveArea { get; set; }
        public string CustomerFeedback { get; set; }
        public string MarketSaleTeamAdvice { get; set; }
        public Nullable<int> AttendenceOwnerCount { get; set; }
        public Nullable<int> AttendencePCCount { get; set; }
        public string OnLineAdPic01 { get; set; }
        public string OnLineAdPic02 { get; set; }
        public string OnLineAdPic03 { get; set; }
        public string OnLineAdPic04 { get; set; }
        public string OnLineAdDesc01 { get; set; }
        public string OnLineAdDesc02 { get; set; }
        public string OnLineAdDesc03 { get; set; }
        public string OnLineAdDesc04 { get; set; }
        public string CarDisplayPic01 { get; set; }
        public string CarDisplayPic02 { get; set; }
        public string CarDisplayPic03 { get; set; }
        public string CarDisplayPic04 { get; set; }
        public string CarDisplayDesc01 { get; set; }
        public string CarDisplayDesc02 { get; set; }
        public string CarDisplayDesc03 { get; set; }
        public string CarDisplayDesc04 { get; set; }
        public string PlacePic01 { get; set; }
        public string PlacePic02 { get; set; }
        public string PlacePic03 { get; set; }
        public string PlacePic04 { get; set; }
        public string PlaceDesc01 { get; set; }
        public string PlaceDesc02 { get; set; }
        public string PlaceDesc03 { get; set; }
        public string PlaceDesc04 { get; set; }
        public string RegisterLiveShowPic01 { get; set; }
        public string RegisterLiveShowPic02 { get; set; }
        public string RegisterLiveShowPic03 { get; set; }
        public string RegisterLiveShowPic04 { get; set; }
        public string RegisterLiveShowDesc01 { get; set; }
        public string RegisterLiveShowDesc02 { get; set; }
        public string RegisterLiveShowDesc03 { get; set; }
        public string RegisterLiveShowDesc04 { get; set; }
        public string CustomerStaffModelPic01 { get; set; }
        public string CustomerStaffModelPic02 { get; set; }
        public string CustomerStaffModelPic03 { get; set; }
        public string CustomerStaffModelPic04 { get; set; }
        public string CustomerStaffModelDesc01 { get; set; }
        public string CustomerStaffModelDesc02 { get; set; }
        public string CustomerStaffModelDesc03 { get; set; }
        public string CustomerStaffModelDesc04 { get; set; }
        public string OthersPic01 { get; set; }
        public string OthersPic02 { get; set; }
        public string OthersPic03 { get; set; }
        public string OthersPic04 { get; set; }
        public string OthersDesc01 { get; set; }
        public string OthersDesc02 { get; set; }
        public string OthersDesc03 { get; set; }
        public string OthersDesc04 { get; set; }
        public Nullable<int> InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public Nullable<int> ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDateTime { get; set; }
    }
}
